language:python
sudo:required

install:
  - sudo apt-get install python=3.7
  - pip install -r ./requirements.txt
  - sudo apt-get install nodejs
  - cd wxapp && npm install

script:
  - cd webapp && python manage.py test
  - cd wxapp && npm test

