language:python
sudo:required

python:
  - "3.7"
nodejs:
  - "10"

install:
  - sudo apt-get install python=3.7
  - pip install -r webapp/requirements.txt
  - sudo apt-get install nodejs
  - cd wxapp && npm install

script:
  - cd webapp && python manage.py test
  - cd wxapp && npm test

