language: python

services:
  - mysql
  - redis-server

sudo: required
branches:
  only:
  - master
  - release
python:
- '3.7'

before_script:
  - echo "USE mysql;\nupdate mysql.user set authentication_string=password('Waqing121!') where user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

jobs:
  include:
  - language: node_js
    node_js: '10'
    install:
    - cd wxapp && npm install
    script:
    - npm test
  - install:
    - pip install -r webapp/backend/requirements.txt
    script:
    - python webapp/backend/manage.py test

before_install:
- openssl aes-256-cbc -K $encrypted_fc68b59f2946_key -iv $encrypted_fc68b59f2946_iv
  -in id_rsa_deploy.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- mysql -e 'create database test;'

addons:
  ssh_known_hosts: 62.234.7.17

after_success:
- ssh ubuntu@$IP 'cd volunteers-tsinghua && git checkout release && git pull && cd webapp && sudo docker-compose restart'
