language: python
sudo: required

branches:
  only:
    - master
    - release

python:
  - "3.7"

jobs:
  include:
    - language: node_js
      node_js: "10"
      install:
        - cd wxapp && npm install
      script:
        - cd wxapp && npm test
    - install:
        - pip install -r webapp/requirements.txt
      script:
        - cd webapp && python manage.py test
