"""empty message

Revision ID: 40b3569df4c1
Revises: f8be0ebde913
Create Date: 2019-11-28 23:10:03.163081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40b3569df4c1'
down_revision = 'f8be0ebde913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activities_ibfk_1', 'activities', type_='foreignkey')
    op.create_foreign_key(None, 'activities', 'teams', ['teamId'], ['id'], ondelete='cascade')
    op.alter_column('messages', 'isRead',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_constraint('messages_ibfk_3', 'messages', type_='foreignkey')
    op.drop_constraint('messages_ibfk_2', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'teams', ['teamId'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'messages', 'users', ['userId'], ['id'], ondelete='cascade')
    op.drop_constraint('useractivities_ibfk_2', 'useractivities', type_='foreignkey')
    op.drop_constraint('useractivities_ibfk_1', 'useractivities', type_='foreignkey')
    op.create_foreign_key(None, 'useractivities', 'users', ['userId'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'useractivities', 'activities', ['activityId'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'useractivities', type_='foreignkey')
    op.drop_constraint(None, 'useractivities', type_='foreignkey')
    op.create_foreign_key('useractivities_ibfk_1', 'useractivities', 'activities', ['activityId'], ['id'])
    op.create_foreign_key('useractivities_ibfk_2', 'useractivities', 'users', ['userId'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_ibfk_2', 'messages', 'teams', ['teamId'], ['id'])
    op.create_foreign_key('messages_ibfk_3', 'messages', 'users', ['userId'], ['id'])
    op.alter_column('messages', 'isRead',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.create_foreign_key('activities_ibfk_1', 'activities', 'teams', ['teamId'], ['id'])
    # ### end Alembic commands ###
