"""empty message

Revision ID: 5737d274e7b4
Revises: e23235708ba1
Create Date: 2019-11-28 22:36:22.988279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5737d274e7b4'
down_revision = 'e23235708ba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('teamId', sa.Integer(), nullable=True))
    op.alter_column('messages', 'isRead',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_constraint('messages_ibfk_2', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'teams', ['teamId'], ['id'])
    op.drop_column('messages', 'notifier')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('notifier', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_ibfk_2', 'messages', 'teams', ['notifier'], ['id'])
    op.alter_column('messages', 'isRead',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('messages', 'teamId')
    # ### end Alembic commands ###
