"""empty message

Revision ID: 92216b6bf339
Revises: 61cec1138627
Create Date: 2019-11-26 15:44:32.485464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92216b6bf339'
down_revision = '61cec1138627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('endtime', sa.DateTime(), nullable=False))
    op.alter_column('messages', 'isRead',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('teams', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('teams', sa.Column('establishedtime', sa.DateTime(), nullable=True))
    op.add_column('teams', sa.Column('teamname', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'teamname')
    op.drop_column('teams', 'establishedtime')
    op.drop_column('teams', 'description')
    op.alter_column('messages', 'isRead',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('activities', 'endtime')
    # ### end Alembic commands ###
