"""empty message

Revision ID: a1563a177888
Revises: 60095e4dec5a
Create Date: 2019-12-09 06:56:49.427180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1563a177888'
down_revision = '60095e4dec5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('isMessage', sa.Boolean(), nullable=True))
    op.add_column('activities', sa.Column('time', sa.DateTime(), nullable=True))
    op.alter_column('activities', 'AID',
               existing_type=mysql.VARCHAR(length=12),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('activities', 'isRead',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('activities', 'thumb',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('messages', 'isRead',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_constraint('messages_ibfk_2', 'messages', type_='foreignkey')
    op.drop_column('messages', 'qrCode')
    op.drop_column('messages', 'teamId')
    op.alter_column('useractivities', 'applytime',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('useractivities', 'isRead',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('users', 'openId',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('users', 'wx',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'wx',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('users', 'openId',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('useractivities', 'isRead',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('useractivities', 'applytime',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.add_column('messages', sa.Column('teamId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('qrCode', mysql.VARCHAR(length=64), nullable=True))
    op.create_foreign_key('messages_ibfk_2', 'messages', 'teams', ['teamId'], ['id'], ondelete='CASCADE')
    op.alter_column('messages', 'isRead',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('activities', 'thumb',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('activities', 'isRead',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('activities', 'AID',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=12),
               existing_nullable=True)
    op.drop_column('activities', 'time')
    op.drop_column('activities', 'isMessage')
    # ### end Alembic commands ###
