"""empty message

Revision ID: ab835dd81484
Revises: 5737d274e7b4
Create Date: 2019-11-28 22:40:10.708857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab835dd81484'
down_revision = '5737d274e7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('useractivities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('activityId', sa.Integer(), nullable=True),
    sa.Column('workdate', sa.DateTime(), nullable=False),
    sa.Column('content', sa.String(length=400), nullable=False),
    sa.Column('applytime', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('applying', 'applyed', 'finished'), nullable=True),
    sa.ForeignKeyConstraint(['activityId'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('activities', 'type',
               existing_type=mysql.ENUM('creating', 'createded', 'finished'),
               type_=sa.Enum('creating', 'created', 'finished'),
               existing_nullable=True)
    op.alter_column('messages', 'isRead',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'isRead',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('activities', 'type',
               existing_type=sa.Enum('creating', 'created', 'finished'),
               type_=mysql.ENUM('creating', 'createded', 'finished'),
               existing_nullable=True)
    op.drop_table('useractivities')
    # ### end Alembic commands ###
