"""empty message

Revision ID: cb9e2447497c
Revises: 
Create Date: 2019-11-23 20:40:30.294295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb9e2447497c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('AID', sa.Integer(), nullable=True),
    sa.Column('thumb', sa.String(length=128), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=128), nullable=False),
    sa.Column('totalRecruits', sa.Integer(), nullable=True),
    sa.Column('appliedRecruits', sa.Integer(), nullable=True),
    sa.Column('qrcode', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Team',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userName', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('avatar', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('openId', sa.String(length=64), nullable=False),
    sa.Column('userName', sa.String(length=16), nullable=False),
    sa.Column('wx', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('avatar', sa.String(length=128), nullable=True),
    sa.Column('schoolID', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('profile', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('notifier', sa.Integer(), nullable=True),
    sa.Column('activityId', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('qrCode', sa.String(length=64), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('isRead', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['activityId'], ['Activity.id'], ),
    sa.ForeignKeyConstraint(['notifier'], ['Team.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TeamActivity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teamId', sa.Integer(), nullable=True),
    sa.Column('activityId', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('applying', 'applyed', 'creating', 'created'), nullable=True),
    sa.ForeignKeyConstraint(['activityId'], ['Activity.id'], ),
    sa.ForeignKeyConstraint(['teamId'], ['Team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserActivity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('activityId', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('applying', 'applyed', 'creating', 'created'), nullable=True),
    sa.ForeignKeyConstraint(['activityId'], ['Activity.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('useractivity')
    op.drop_table('message')
    op.drop_table('teamactivity')
    op.drop_table('user')
    op.drop_table('activity')
    op.drop_table('team')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('userName', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('avatar', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('activity',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('AID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('thumb', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('time', mysql.DATETIME(), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('totalRecruits', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('appliedRecruits', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('qrcode', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('openId', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('userName', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('wx', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('avatar', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('schoolID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('phone', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('department', mysql.TEXT(), nullable=True),
    sa.Column('profile', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('teamactivity',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('teamId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('activityId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type', mysql.ENUM('applying', 'applyed', 'creating', 'created'), nullable=True),
    sa.ForeignKeyConstraint(['activityId'], ['activity.id'], name='teamactivity_ibfk_2'),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], name='teamactivity_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('message',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('userId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('notifier', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('activityId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('qrCode', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('time', mysql.DATETIME(), nullable=True),
    sa.Column('isRead', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('(`isRead` in (0,1))', name='message_chk_1'),
    sa.ForeignKeyConstraint(['activityId'], ['activity.id'], name='message_ibfk_3'),
    sa.ForeignKeyConstraint(['notifier'], ['team.id'], name='message_ibfk_2'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name='message_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('useractivity',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('userId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('activityId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type', mysql.ENUM('applying', 'applyed', 'creating', 'created'), nullable=True),
    sa.ForeignKeyConstraint(['activityId'], ['activity.id'], name='useractivity_ibfk_2'),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name='useractivity_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('UserActivity')
    op.drop_table('TeamActivity')
    op.drop_table('Message')
    op.drop_table('User')
    op.drop_table('Team')
    op.drop_table('Activity')
    # ### end Alembic commands ###
