"""empty message

Revision ID: ddfb549efed3
Revises: 34f6ad16f5eb
Create Date: 2019-12-09 09:13:10.119172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddfb549efed3'
down_revision = '34f6ad16f5eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'AID',
               existing_type=mysql.VARCHAR(length=12),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('activities', 'isRead',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('messages', 'isRead',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_constraint('messages_ibfk_2', 'messages', type_='foreignkey')
    op.drop_column('messages', 'teamId')
    op.drop_column('messages', 'qrCode')
    op.drop_column('useractivities', 'isRead')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('useractivities', sa.Column('isRead', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('qrCode', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('messages', sa.Column('teamId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('messages_ibfk_2', 'messages', 'teams', ['teamId'], ['id'], ondelete='CASCADE')
    op.alter_column('messages', 'isRead',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('activities', 'isRead',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('activities', 'AID',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=12),
               existing_nullable=True)
    # ### end Alembic commands ###
