"""empty message

Revision ID: eb2525d577d5
Revises: 92216b6bf339
Create Date: 2019-11-28 21:13:28.083945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb2525d577d5'
down_revision = '92216b6bf339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teamactivities')
    op.add_column('activities', sa.Column('manageemail', sa.String(length=70), nullable=False))
    op.add_column('activities', sa.Column('manageperson', sa.String(length=70), nullable=False))
    op.add_column('activities', sa.Column('managephone', sa.String(length=70), nullable=False))
    op.add_column('activities', sa.Column('starttime', sa.DateTime(), nullable=False))
    op.add_column('activities', sa.Column('teamId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'activities', 'teams', ['teamId'], ['id'])
    op.drop_column('activities', 'time')
    op.drop_column('activities', 'description')
    op.alter_column('messages', 'isRead',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_column('teams', 'userName')
    op.add_column('useractivities', sa.Column('applytime', sa.DateTime(), nullable=False))
    op.add_column('useractivities', sa.Column('content', sa.String(length=400), nullable=False))
    op.add_column('useractivities', sa.Column('workdate', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('useractivities', 'workdate')
    op.drop_column('useractivities', 'content')
    op.drop_column('useractivities', 'applytime')
    op.add_column('teams', sa.Column('userName', mysql.VARCHAR(length=64), nullable=False))
    op.alter_column('messages', 'isRead',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.add_column('activities', sa.Column('description', mysql.VARCHAR(length=400), nullable=False))
    op.add_column('activities', sa.Column('time', mysql.DATETIME(), nullable=False))
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_column('activities', 'teamId')
    op.drop_column('activities', 'starttime')
    op.drop_column('activities', 'managephone')
    op.drop_column('activities', 'manageperson')
    op.drop_column('activities', 'manageemail')
    op.create_table('teamactivities',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('teamId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('activityId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type', mysql.ENUM('creating', 'created'), nullable=True),
    sa.ForeignKeyConstraint(['activityId'], ['activities.id'], name='teamactivities_ibfk_1'),
    sa.ForeignKeyConstraint(['teamId'], ['teams.id'], name='teamactivities_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
