"""empty message

Revision ID: f068e9839cdb
Revises: f37a308a06e9
Create Date: 2019-11-25 16:50:08.650378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f068e9839cdb'
down_revision = 'f37a308a06e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adminuser')
    op.add_column('activities', sa.Column('AID', sa.Integer(), nullable=True))
    op.alter_column('activities', 'content',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=400),
               existing_nullable=False)
    op.alter_column('activities', 'description',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=400),
               existing_nullable=False)
    op.alter_column('activities', 'location',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('activities', 'title',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=70),
               existing_nullable=False)
    op.alter_column('messages', 'isRead',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('teams', sa.Column('password', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'password')
    op.alter_column('messages', 'isRead',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('activities', 'title',
               existing_type=sa.String(length=70),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)
    op.alter_column('activities', 'location',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('activities', 'description',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('activities', 'content',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=False)
    op.drop_column('activities', 'AID')
    op.create_table('adminuser',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`active` in (0,1))', name='adminuser_chk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
