version: '3'
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=zhizaitsinghua
      - MYSQL_DATABASE=volunteers
    restart: always
    volumes:
      - ~/data:/var/lib/mysql
  flask:
    image: flask-nginx-uwsgi
    restart: always
    ports:
      - "1080:80"
    links:
      - mysql
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./backend:/backend
      - ./start.sh:/start.sh



