version: '3'
services:
  redis:
    image: redis
    restart: always
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=zhizaitsinghua
      - MYSQL_DATABASE=volunteers
    restart: always
    volumes:
      - ~/data:/var/lib/mysql
  flask:
    build: ./
    restart: always
    ports:
      - "1080:80"
    links:
      - mysql
      - redis
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./backend:/backend
      - ./start.sh:/start.sh



