runserver:
	python backend/manage.py runserver --host 0.0.0.0 --port 80 --threaded

test:
	python backend/manage.py test

init:
	python backend/manage.py db init

migrate:
	python backend/manage.py db migrate

upgrade:
	python backend/manage.py db upgrade